"use client";

import { useState } from "react";
import { Copy, Check, ExternalLink, ChevronDown, ChevronUp } from "lucide-react";
import type { OutputLanguage } from "@/types/algo-builder";

const C = "var(--tool-accent)";

interface ExportBridgeProps {
  code:        string;
  language:    OutputLanguage;
  instrument:  string;
  timeframe:   string;
  description: string;
}

const GUIDE_CARDS = [
  {
    title: "TradingView · Pine Script",
    icon: "🌲",
    show: "always" as const,
    steps: [
      "Open TradingView → Pine Editor (bottom panel, click 'Open Pine Editor')",
      "Paste your generated code",
      "Click 'Add to chart' → the strategy loads immediately",
      "Open Strategy Tester tab to run the full backtest",
    ],
    cta: { label: "Open TradingView →", href: "https://www.tradingview.com/?aff_id=165855" },
  },
  {
    title: "Interactive Brokers · Python",
    icon: "📊",
    show: "python" as const,
    steps: [
      "Install dependency: pip install ib_insync backtrader",
      "Enable API in TWS/Gateway: File → Global Configuration → API → Enable ActiveX",
      "Default port: 7497 (live), 7496 (paper trading)",
      "Replace the Backtrader data feed with IBBroker() — see Drawdown IB guide",
    ],
    cta: { label: "IB Setup Guide →", href: "/guides/ib-api" },
  },
  {
    title: "MetaTrader 5 · Python Bridge",
    icon: "⚡",
    show: "python" as const,
    steps: [
      "Install dependency: pip install MetaTrader5",
      "Launch MT5 terminal and enable 'Allow automated trading'",
      "Connect: mt5.initialize(path='C:/MT5/terminal.exe')",
      "Replace Backtrader execution with mt5.order_send() calls",
    ],
    cta: { label: "MT5 Guide (coming soon)", href: "#" },
  },
];

export function ExportBridge({
  code, language, instrument, timeframe, description,
}: ExportBridgeProps) {
  const [copiedHeader, setCopiedHeader] = useState(false);
  const [open, setOpen]                 = useState(false);

  function buildHeaderComment(): string {
    const langLine = language === "pine_script"
      ? "// Language: Pine Script v6 (TradingView)"
      : "# Language: Python / Backtrader";
    const commentChar = language === "pine_script" ? "//" : "#";
    const lines = [
      `${commentChar} ─────────────────────────────────────────────────────────`,
      `${commentChar} Generated by Drawdown QuantCoder AI`,
      `${commentChar} Strategy: ${description.slice(0, 60).replace(/\n/g, " ")}${description.length > 60 ? "…" : ""}`,
      `${commentChar} Generated: ${new Date().toISOString().split("T")[0]}`,
      `${commentChar} Instrument: ${instrument || "—"}  |  Timeframe: ${timeframe || "—"}`,
      langLine,
      `${commentChar} drawdown.trading  |  Trade the Truth`,
      `${commentChar} ─────────────────────────────────────────────────────────`,
      "",
    ].join("\n");
    return lines + code;
  }

  function copyWithHeader() {
    navigator.clipboard.writeText(buildHeaderComment()).then(() => {
      setCopiedHeader(true);
      setTimeout(() => setCopiedHeader(false), 2500);
    });
  }

  const visibleCards = GUIDE_CARDS.filter(
    c => c.show === "always" || c.show === language
  );

  return (
    <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm">
      {/* Header */}
      <button
        onClick={() => setOpen(v => !v)}
        className="w-full flex items-center justify-between px-4 py-3 text-left bg-white hover:bg-gray-50 transition-colors"
      >
        <div>
          <p className="text-[11px] font-mono font-bold uppercase tracking-widest text-gray-900">
            Export & Deploy
          </p>
          <p className="text-[9px] font-mono text-gray-400 mt-0.5">
            Integration guides for TradingView, IBKR, and MT5
          </p>
        </div>
        {open
          ? <ChevronUp   className="w-4 h-4 text-gray-400" />
          : <ChevronDown className="w-4 h-4 text-gray-400" />}
      </button>

      {open && (
        <div className="p-4 space-y-4 bg-white border-t border-gray-100">
 
          {/* Copy with header */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 px-4 py-3 bg-[#f5f3ff] border border-[#ddd6fe] rounded-lg">
            <div>
              <p className="text-[11px] font-mono text-gray-900 font-bold">Copy as TradingView-ready</p>
              <p className="text-[9px] font-mono text-gray-500 mt-0.5">
                Adds a metadata header (strategy name, date, instrument, language)
              </p>
            </div>
            <button
              onClick={copyWithHeader}
              className="flex items-center gap-2 px-4 py-2 text-[10px] font-mono font-bold uppercase tracking-wider transition-all rounded-lg shrink-0 justify-center"
              style={{
                backgroundColor: copiedHeader ? "var(--tool-accent-tint)" : C,
                color: copiedHeader ? "var(--tool-accent-text)" : "#ffffff",
                border: copiedHeader ? "1px solid var(--tool-accent-border)" : "none",
              }}
            >
              {copiedHeader
                ? <><Check className="w-3.5 h-3.5" /> Copied with header!</>
                : <><Copy  className="w-3.5 h-3.5" /> Copy with Header</>}
            </button>
          </div>

          {/* Guide cards */}
          <div className={`grid grid-cols-1 gap-3 ${visibleCards.length > 1 ? "md:grid-cols-2 lg:grid-cols-3" : ""}`}>
            {visibleCards.map(card => (
              <div
                key={card.title}
                className="flex flex-col bg-[#f9fafb] border border-gray-200 rounded-lg overflow-hidden"
              >
                <div className="px-4 py-3 border-b border-gray-200 bg-white">
                  <p className="text-[11px] font-mono font-bold text-gray-900">
                    {card.icon} {card.title}
                  </p>
                </div>
                <ol className="flex-1 px-4 py-3 space-y-2.5">
                  {card.steps.map((step, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span
                        className="text-[8px] font-mono font-bold w-4 h-4 flex items-center justify-center shrink-0 mt-0.5 rounded-full"
                        style={{ backgroundColor: "var(--tool-accent-tint)", color: "var(--tool-accent-text)", border: "1px solid var(--tool-accent-border)" }}
                      >
                        {i + 1}
                      </span>
                      <span className="text-[10px] font-mono text-gray-600 leading-snug">{step}</span>
                    </li>
                  ))}
                </ol>
                <div className="px-4 pb-3 bg-[#f9fafb]">
                  <a
                    href={card.cta.href}
                    target={card.cta.href.startsWith("http") ? "_blank" : undefined}
                    rel={card.cta.href.startsWith("http") ? "noopener noreferrer" : undefined}
                    className="flex items-center gap-1.5 text-[10px] font-mono uppercase tracking-wider transition-opacity hover:opacity-70 font-bold"
                    style={{ color: "var(--tool-accent-text)" }}
                  >
                    {card.cta.label}
                    {card.cta.href.startsWith("http") && <ExternalLink className="w-3 h-3" />}
                  </a>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
