import { createInternalSupabase } from "@/lib/supabase/server";
import Link from "next/link";
// Stripe migration report is generated by running:
//   node scripts/stripe-migration-dry-run.mjs
// Once generated, the admin can view stripe-migration-report.json in the scripts/ folder.
import { 
  ShieldAlert, 
  Target, 
  Users, 
  Settings, 
  TrendingDown, 
  ArrowRight,
  TrendingUp,
  CreditCard,
  Layers,
  Sparkles,
  HelpCircle
} from "lucide-react";

export const dynamic = "force-dynamic";

interface WaitlistItem {
  id: string;
  email: string;
  name: string | null;
  current_tier: string | null;
  reason: string | null;
  status: string;
  created_at: string;
}

export default async function AdminCommercialPage() {
  const supabase = createInternalSupabase();

  // 1. Fetch products & prices from commercial catalogue
  const { data: dbProducts } = await supabase
    .from("commercial_products")
    .select("*")
    .order("display_order", { ascending: true });

  const { data: dbPrices } = await supabase
    .from("product_prices")
    .select("*");

  // 2. Fetch Floor capacity & waitlist
  const { data: capacityConfig } = await supabase
    .from("floor_capacity_config")
    .select("*")
    .single();

  const { data: waitlistItems } = await supabase
    .from("floor_waitlist")
    .select("*")
    .order("created_at", { ascending: false });

  // 3. Stripe migration report — generated externally via:
  //    node scripts/stripe-migration-dry-run.mjs
  // The report is written to scripts/stripe-migration-report.json
  // Displayed here as a placeholder; in production wire this via a DB table or signed URL.
  const migrationReport: any = null;

  // 4. Fetch subscription migration logs
  const { data: migrationLogs } = await supabase
    .from("subscription_migration_log")
    .select("*")
    .order("executed_at", { ascending: false })
    .limit(10);

  return (
    <div className="space-y-10">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <span className="text-[10px] font-mono font-bold uppercase tracking-widest text-mkt-i3 block mb-1">
            // DRAWDOWN SYSTEM CONTROLS
          </span>
          <h1 className="text-3xl font-display font-extrabold uppercase tracking-tight text-mkt-ink">
            Commercial &amp; Pricing Centre
          </h1>
        </div>
      </div>

      {/* Grid: Overview cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="p-6 bg-white border border-slate-200 rounded-xl space-y-2 shadow-sm">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-mono font-bold uppercase tracking-widest text-slate-500">
              Active Catalogue Products
            </span>
            <Layers className="w-5 h-5 text-slate-400" />
          </div>
          <p className="text-3xl font-black font-mono text-slate-900">
            {dbProducts?.length || 6}
          </p>
          <p className="text-xs text-slate-500 font-sans">
            Centralized source of truth mapped from database.
          </p>
        </div>

        <div className="p-6 bg-white border border-slate-200 rounded-xl space-y-2 shadow-sm">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-mono font-bold uppercase tracking-widest text-slate-500">
              Floor Waitlist
            </span>
            <Users className="w-5 h-5 text-slate-400" />
          </div>
          <p className="text-3xl font-black font-mono text-slate-900">
            {waitlistItems?.length || 0}
          </p>
          <p className="text-xs text-slate-500 font-sans">
            Capped at {capacityConfig?.max_active || 20} active subscribers.
          </p>
        </div>

        <div className="p-6 bg-white border border-slate-200 rounded-xl space-y-2 shadow-sm">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-mono font-bold uppercase tracking-widest text-slate-500">
              Projected MRR Delta (£99/mo)
            </span>
            <TrendingDown className="w-5 h-5 text-amber-500" />
          </div>
          <p className="text-3xl font-black font-mono text-amber-600">
            {migrationReport ? `£${migrationReport.netMRRDifference}` : "Pending"}
          </p>
          <p className="text-xs text-slate-500 font-sans">
            MRR adjustment on Edge legacy subscription updates.
          </p>
        </div>
      </div>

      {/* Catalogue List */}
      <section className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50">
          <h2 className="text-sm font-mono font-bold uppercase tracking-wider text-slate-800">
            Commercial Product Catalogue
          </h2>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-200 text-[10px] font-mono font-bold text-slate-500 uppercase tracking-widest bg-slate-50/50">
                <th className="p-4">Product / Type</th>
                <th className="p-4">Status</th>
                <th className="p-4">GBP Prices</th>
                <th className="p-4">Stripe product id</th>
                <th className="p-4">Admin description</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-sm font-sans">
              {dbProducts?.map((product) => {
                const prodPrices = dbPrices?.filter(p => p.product_id === product.id) || [];
                return (
                  <tr key={product.id} className="hover:bg-slate-50/50">
                    <td className="p-4">
                      <span className="font-bold text-slate-900 block">{product.name}</span>
                      <span className="text-[10px] font-mono text-slate-500 uppercase">{product.product_type}</span>
                    </td>
                    <td className="p-4">
                      <span className={`inline-flex px-2 py-0.5 rounded text-[9px] font-mono font-bold uppercase border ${
                        product.status === "active" ? "bg-emerald-50 border-emerald-200 text-emerald-700" :
                        product.status === "legacy_grandfathered" ? "bg-amber-50 border-amber-200 text-amber-700" :
                        "bg-slate-100 border-slate-300 text-slate-700"
                      }`}>
                        {product.status}
                      </span>
                    </td>
                    <td className="p-4 font-mono text-xs">
                      {prodPrices.map(p => (
                        <div key={p.id} className="mb-0.5">
                          £{(p.amount_pence / 100).toLocaleString()} / {p.interval}
                        </div>
                      ))}
                    </td>
                    <td className="p-4 font-mono text-xs text-slate-400 max-w-[200px] truncate">
                      {product.stripe_product_id || "none"}
                    </td>
                    <td className="p-4 text-xs text-slate-600 max-w-[250px] leading-relaxed">
                      {product.admin_note || product.description}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </section>

      {/* Waitlist Management */}
      <section className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50 flex justify-between items-center">
          <h2 className="text-sm font-mono font-bold uppercase tracking-wider text-slate-800">
            The Floor Waitlist ({waitlistItems?.length || 0})
          </h2>
          <span className="text-xs font-mono font-bold text-slate-500">
            CAP: {capacityConfig?.current_active || 0} / {capacityConfig?.max_active || 20}
          </span>
        </div>
        <div className="overflow-x-auto">
          {waitlistItems && waitlistItems.length > 0 ? (
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-200 text-[10px] font-mono font-bold text-slate-500 uppercase tracking-widest bg-slate-50/50">
                  <th className="p-4">Candidate</th>
                  <th className="p-4">Current Tier</th>
                  <th className="p-4">Waitlist Reason</th>
                  <th className="p-4">Status</th>
                  <th className="p-4">Applied At</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-sm font-sans">
                {waitlistItems.map((item: WaitlistItem) => (
                  <tr key={item.id} className="hover:bg-slate-50/50">
                    <td className="p-4">
                      <span className="font-bold text-slate-900 block">{item.name || "Anonymous"}</span>
                      <span className="text-xs text-slate-500 font-mono">{item.email}</span>
                    </td>
                    <td className="p-4 font-mono text-xs uppercase">
                      {item.current_tier || "free"}
                    </td>
                    <td className="p-4 text-xs text-slate-600 max-w-[300px] leading-relaxed">
                      {item.reason || "none"}
                    </td>
                    <td className="p-4">
                      <span className={`inline-flex px-2.5 py-0.5 rounded text-[9px] font-mono font-bold uppercase ${
                        item.status === "pending" ? "bg-amber-50 text-amber-700 border border-amber-200" :
                        item.status === "offered" ? "bg-blue-50 text-blue-700 border border-blue-200" :
                        "bg-emerald-50 text-emerald-700 border border-emerald-200"
                      }`}>
                        {item.status}
                      </span>
                    </td>
                    <td className="p-4 text-xs font-mono text-slate-500">
                      {new Date(item.created_at).toLocaleDateString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <div className="p-8 text-center text-slate-500 text-xs font-mono">
              Waitlist is currently empty.
            </div>
          )}
        </div>
      </section>

      {/* Migration Dry-Run & Audit Log */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Stripe Migration Status */}
        <section className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="px-6 py-4 border-b border-slate-200 bg-slate-50">
            <h2 className="text-sm font-mono font-bold uppercase tracking-wider text-slate-800">
              Stripe Migration Summary
            </h2>
          </div>
          <div className="p-6 space-y-6">
            {migrationReport ? (
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4 text-xs font-mono">
                  <div className="p-3 bg-slate-50 border border-slate-200 rounded">
                    <span className="text-slate-500 uppercase block mb-1">Affected Edge Subs</span>
                    <span className="text-lg font-bold text-slate-900">{migrationReport.affectedSubscribers}</span>
                  </div>
                  <div className="p-3 bg-slate-50 border border-slate-200 rounded">
                    <span className="text-slate-500 uppercase block mb-1">Annual Delta Impact</span>
                    <span className="text-lg font-bold text-amber-600">£{migrationReport.netARRDifference.toLocaleString()}</span>
                  </div>
                </div>

                <div className="space-y-2">
                  <span className="text-[10px] font-mono font-bold uppercase text-slate-500 tracking-wider block">
                    Migration Actions Plan
                  </span>
                  <div className="max-h-[200px] overflow-y-auto border border-slate-200 rounded divide-y divide-slate-100">
                    {migrationReport.proposedMigrationActions.map((action: any, idx: number) => (
                      <div key={idx} className="p-3 flex justify-between items-center text-xs font-sans hover:bg-slate-50">
                        <div>
                          <span className="font-bold text-slate-800 block">{action.email || "mock_customer"}</span>
                          <span className="text-[10px] font-mono text-slate-500">{action.subscriptionId}</span>
                        </div>
                        <div className="text-right">
                          <span className="font-bold text-red-500 font-mono">£{action.oldPrice} → £{action.newPrice}</span>
                          <span className="text-[10px] text-emerald-600 block">Save £50/mo</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              <div className="text-center py-8 space-y-3">
                <ShieldAlert className="w-8 h-8 text-amber-500 mx-auto" />
                <p className="text-xs font-mono text-slate-500">
                  Stripe migration dry-run report is not yet generated.
                </p>
                <div className="text-xs text-slate-400 font-sans max-w-sm mx-auto leading-relaxed">
                  Run the background migration task or check credentials to populate the MRR dry-run simulation matrix.
                </div>
              </div>
            )}
          </div>
        </section>

        {/* Audit Log */}
        <section className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
          <div className="px-6 py-4 border-b border-slate-200 bg-slate-50">
            <h2 className="text-sm font-mono font-bold uppercase tracking-wider text-slate-800">
              Subscription Migration Audit Log
            </h2>
          </div>
          <div className="overflow-x-auto">
            {migrationLogs && migrationLogs.length > 0 ? (
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="border-b border-slate-200 text-[10px] font-mono font-bold text-slate-500 uppercase tracking-widest bg-slate-50/50">
                    <th className="p-4">Action</th>
                    <th className="p-4">Old/New Tier</th>
                    <th className="p-4">Admin Notes</th>
                    <th className="p-4">Logged At</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-xs font-sans">
                  {migrationLogs.map((log: any) => (
                    <tr key={log.id} className="hover:bg-slate-50/50">
                      <td className="p-4 font-mono font-bold uppercase text-slate-800">
                        {log.action}
                      </td>
                      <td className="p-4 font-mono text-[10px]">
                        {log.old_tier || "none"} → {log.new_tier || "none"}
                      </td>
                      <td className="p-4 text-slate-600 max-w-[200px] leading-relaxed">
                        {log.notes || "none"}
                      </td>
                      <td className="p-4 font-mono text-slate-400">
                        {new Date(log.executed_at).toLocaleString()}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <div className="p-8 text-center text-slate-500 text-xs font-mono">
                No recent subscription logs recorded.
              </div>
            )}
          </div>
        </section>
      </div>
    </div>
  );
}
