-- ==============================================================================
-- Migration: 20260911_consolidate_daily_brief_readers.sql
-- Description: Architecture Decision Record for daily_briefs vs daily_briefings.
--
-- Audit Finding (Prompt 02 Phase 2B):
-- - `daily_briefs` has 0 rows in production. Originally created for email newsletter format.
-- - `daily_briefings` has 80+ rows in production, generated daily via cron/daily-report.
--
-- Decision:
-- 1. `daily_briefings` is the authoritative live table for the platform dashboard,
--    intelligence pages, and homepage excerpts.
-- 2. `daily_briefs` is retained exclusively for any standalone email newsletter pipeline;
--    it is NOT dropped to avoid destructive operations on existing schemas.
-- 3. Codebase readers (dashboard/page.tsx, PetesDailyTakeExcerpt.tsx) have been
--    redirected to query `daily_briefings`.
-- ==============================================================================

COMMENT ON TABLE daily_briefings IS 'Authoritative daily macro & market intelligence briefings generated by /api/cron/daily-report.';
COMMENT ON TABLE daily_briefs IS 'Legacy email newsletter brief table. Not consumed by main dashboard or homepage intelligence widgets.';
